# Site settings
title: Wenqing Qian
description: Every day is a good day.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://conchaespina.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: ConchaEspina
user_description: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform.
user_title: Software Engineer
email: claireq99@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: lorem_ipsum
# facebook_username: lorem_ipsum
# linkedin_username: lorem_ipsum
# github_username:  lorem_ipsum
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
