# Site settings
title: Wenqing's Homepage
description: Every day is a good day.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://conchaespina.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Wenqing Qian
user_description: I am an undergraduate student majoring in statistics at Fudan University.
# user_title: Software Engineer
email: claireq99@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: lorem_ipsum
# facebook_username: lorem_ipsum
# linkedin_username: lorem_ipsum
github_username:  conchaespina
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
